//! Pipeline traits and core types.
//!
//! Defines the `ProcessingStep` trait and associated types for building
//! extensible image processing pipelines.

use crate::config::Config;
use crate::face_processing::types::{HeadPose, Landmarks};
use crate::immich_api::FaceData;
use async_trait::async_trait;
use bytes::Bytes;
use image::DynamicImage;
use std::collections::HashMap;
use std::fmt;

/// Outcome of a pipeline step execution.
#[derive(Debug)]
pub enum StepOutcome {
    /// Continue to the next step with the updated context.
    Continue(PipelineContext),
    /// Skip this image with the given reason.
    Skip { reason: String, detail: Option<String> },
    /// An error occurred during processing.
    Error(String),
}

/// Values computed by pipeline steps that can be shared with subsequent steps.
#[derive(Debug, Clone)]
pub enum ComputedValue {
    /// A floating-point value (e.g., brightness, EAR).
    Float(f32),
    /// An integer value (e.g., face size in pixels).
    Int(i32),
    /// A boolean value (e.g., eyes_open).
    Bool(bool),
    /// A string value.
    String(String),
    /// Head pose estimation result (yaw, pitch, roll).
    HeadPose(HeadPose),
    /// Facial landmarks (68 points).
    Landmarks(Box<Landmarks>),
}

impl ComputedValue {
    /// Get as f32 if this is a Float variant.
    pub fn as_float(&self) -> Option<f32> {
        match self {
            ComputedValue::Float(v) => Some(*v),
            _ => None,
        }
    }

    /// Get as i32 if this is an Int variant.
    pub fn as_int(&self) -> Option<i32> {
        match self {
            ComputedValue::Int(v) => Some(*v),
            _ => None,
        }
    }

    /// Get as bool if this is a Bool variant.
    pub fn as_bool(&self) -> Option<bool> {
        match self {
            ComputedValue::Bool(v) => Some(*v),
            _ => None,
        }
    }

    /// Get as &str if this is a String variant.
    pub fn as_str(&self) -> Option<&str> {
        match self {
            ComputedValue::String(v) => Some(v),
            _ => None,
        }
    }

    /// Get as HeadPose if this is a HeadPose variant.
    pub fn as_head_pose(&self) -> Option<&HeadPose> {
        match self {
            ComputedValue::HeadPose(v) => Some(v),
            _ => None,
        }
    }

    /// Get as Landmarks if this is a Landmarks variant.
    pub fn as_landmarks(&self) -> Option<&Landmarks> {
        match self {
            ComputedValue::Landmarks(v) => Some(v),
            _ => None,
        }
    }
}

/// Context passed through the pipeline, carrying data between steps.
#[derive(Debug)]
pub struct PipelineContext {
    /// The asset ID from Immich.
    pub asset_id: String,
    /// Timestamp for sorting/naming output files.
    pub timestamp: String,
    /// Raw image bytes (before decoding).
    pub raw_bytes: Option<Bytes>,
    /// Decoded image (after decode step).
    pub image: Option<DynamicImage>,
    /// Face bounding box and metadata from Immich.
    pub face_data: FaceData,
    /// Values computed by previous steps (e.g., brightness, landmarks).
    pub computed: HashMap<String, ComputedValue>,
    /// Debug images generated by steps (step_id -> debug image).
    pub debug_images: HashMap<String, DynamicImage>,
}

impl PipelineContext {
    /// Create a new pipeline context.
    pub fn new(asset_id: String, timestamp: String, face_data: FaceData) -> Self {
        Self {
            asset_id,
            timestamp,
            raw_bytes: None,
            image: None,
            face_data,
            computed: HashMap::new(),
            debug_images: HashMap::new(),
        }
    }

    /// Set the raw image bytes.
    pub fn with_bytes(mut self, bytes: Bytes) -> Self {
        self.raw_bytes = Some(bytes);
        self
    }

    /// Set the decoded image.
    pub fn with_image(mut self, image: DynamicImage) -> Self {
        self.image = Some(image);
        self
    }

    /// Add a computed value.
    pub fn set_computed(&mut self, key: impl Into<String>, value: ComputedValue) {
        self.computed.insert(key.into(), value);
    }

    /// Get a computed value.
    pub fn get_computed(&self, key: &str) -> Option<&ComputedValue> {
        self.computed.get(key)
    }

    /// Add a debug image for a step.
    pub fn add_debug_image(&mut self, step_id: impl Into<String>, image: DynamicImage) {
        self.debug_images.insert(step_id.into(), image);
    }
}

/// A single step in the processing pipeline.
///
/// Steps can be:
/// - **Validators**: Skip the image if a condition fails (return `StepOutcome::Skip`)
/// - **Transformers**: Modify the image (update `ctx.image`)
/// - **Computers**: Calculate values for later steps (update `ctx.computed`)
#[async_trait]
pub trait ProcessingStep: Send + Sync {
    /// Unique identifier for this step (used in skip stats and debug output).
    fn id(&self) -> &'static str;

    /// Human-readable name for display.
    fn name(&self) -> &'static str;

    /// Execute this step on the given context.
    ///
    /// Returns:
    /// - `StepOutcome::Continue(ctx)` to proceed to the next step
    /// - `StepOutcome::Skip { reason, detail }` to skip this image
    /// - `StepOutcome::Error(msg)` if processing failed
    async fn execute(&self, ctx: PipelineContext, config: &Config) -> StepOutcome;

    /// Generate a debug visualization for this step (optional).
    ///
    /// Called after `execute()` if debug mode is enabled and the step
    /// returned `Continue`. The returned image is saved to the debug folder.
    fn debug_visualize(&self, _ctx: &PipelineContext) -> Option<DynamicImage> {
        None
    }
}

impl fmt::Debug for dyn ProcessingStep {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_struct("ProcessingStep")
            .field("id", &self.id())
            .field("name", &self.name())
            .finish()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_computed_value_conversions() {
        let float_val = ComputedValue::Float(0.5);
        assert_eq!(float_val.as_float(), Some(0.5));
        assert_eq!(float_val.as_int(), None);

        let int_val = ComputedValue::Int(100);
        assert_eq!(int_val.as_int(), Some(100));
        assert_eq!(int_val.as_float(), None);

        let bool_val = ComputedValue::Bool(true);
        assert_eq!(bool_val.as_bool(), Some(true));

        let str_val = ComputedValue::String("test".to_string());
        assert_eq!(str_val.as_str(), Some("test"));
    }

    #[test]
    fn test_pipeline_context_computed_values() {
        let face_data = FaceData {
            bounding_box_x1: 0.0,
            bounding_box_y1: 0.0,
            bounding_box_x2: 100.0,
            bounding_box_y2: 100.0,
            image_width: 1920,
            image_height: 1080,
        };

        let mut ctx = PipelineContext::new(
            "asset123".to_string(),
            "2024-01-15".to_string(),
            face_data,
        );

        ctx.set_computed("brightness", ComputedValue::Float(0.65));
        ctx.set_computed("face_size", ComputedValue::Int(150));

        assert_eq!(
            ctx.get_computed("brightness").and_then(|v| v.as_float()),
            Some(0.65)
        );
        assert_eq!(
            ctx.get_computed("face_size").and_then(|v| v.as_int()),
            Some(150)
        );
        assert!(ctx.get_computed("nonexistent").is_none());
    }
}
